docs: Document Overview Data Pipeline
OpenThaiGPT/openthaigpt-pretraining pull request #309
Opened 2023-09-25 04:28 UTC by kwankoravich

## Why this PR
Why we need this PR?

## Changes
- Write some changes here

## Related Issues
Close #

## Checklist
- [ ] PR should be in the [Naming convention](../../docs/PR_NAMING.md)
- [ ] Assign yourself in to Assigneees
- [ ] Tag related issues
- [ ] Constants name should be ALL_CAPITAL, function name should be snake_case, and class name should be CamelCase
- [ ] complex function/algorithm should have [Docstring](https://peps.python.org/pep-0257/)
- [ ] 1 PR should not have more than 200 lines changes (Exception for test files). If more than that please open multiple PRs
- [ ] At least PR reviewer must come from the task's team (model, eval, data)

2023-09-25 05:15 UTC, new5558 requested changes

2023-09-25 05:15 UTC, new5558 commented on src/data/README.md
> +3. Consolidate all JSONL datasets into a single file. This pipeline can be found at: `src/data/scripts/merge_jsonl/` to merge JSONL file
Only some data such as oscar, require merge jsonl. When we merge jsonl we do it seperately for each data.


For example
- oscar
    - oscar22.jsonl
    - oscar23.jsonl
    - oscar19.jsonl
- pantip
    - pantip2g.jsonl
    - pantip3g.jsonl
    

we need to run merge jsonl code two time targeting pantip and oscar seperately.


The result will be:
- oscar
    - oscar22.jsonl
    - oscar23.jsonl
    - oscar19.jsonl
    - oscarall.jsonl
- pantip
    - pantip2g.jsonl
    - pantip3g.jsonl
    - pantipall.jsonl
    - 
    
This is ugly, but it is our current pipeline works

2023-09-25 05:15 UTC, new5558 commented on src/data/README.md
> +5. Anonymize Sensitive Data, which may include personal and residential information, in compliance with PDPA regulations.
No we anonymize last (after decontaminate)

and we also need to convert jsonl to huggingface dataset first before deduplicate starts https://github.com/OpenThaiGPT/openthaigpt-pretraining/tree/main/src/data/scripts/huggingface_create

2023-09-25 05:15 UTC, new5558 commented on src/data/README.md
> +3. Consolidate all JSONL datasets into a single file. This pipeline can be found at: `src/data/scripts/merge_jsonl/` to merge JSONL file
Also please add path to blind pdpa code https://github.com/OpenThaiGPT/openthaigpt-pretraining/tree/main/src/data/scripts/blind_pdpa

2023-09-25 05:15 UTC, new5558 commented on src/data/README.md
> +
Please change from `src/data/scripts/…` to link to folder that contain the scripts on github

2023-09-25 05:15 UTC, new5558 commented on src/data/README.md
> +## Workflow
Can we have some diagram to explain the worlflow. We may export it from our figjam

2023-09-25 05:31 UTC, new5558 commented on src/data/README.md
> +2. Transform plain text data from each raw data source into the JSONL format.
We also have scripts for this krub

not all script is already in git for now, but the one you should include in this readme are: https://github.com/OpenThaiGPT/openthaigpt-pretraining/tree/main/src/data/scripts/pantip_2G
https://github.com/OpenThaiGPT/openthaigpt-pretraining/tree/main/src/data/scripts/pantip_3G
https://github.com/OpenThaiGPT/openthaigpt-pretraining/tree/main/src/data/scripts/internet

2023-09-25 05:34 UTC, new5558 commented on src/data/README.md
> +1. Obtain Raw Data in various formats such as CSV, PDF, etc., and convert it into plain text format.
Not all data obtaining method are listed on git for now, but at least we should mentioned https://github.com/OpenThaiGPT/openthaigpt-pretraining/tree/main/src/data/scripts/crawl_thaigov in this readme

2023-10-02 17:09 UTC, new5558 approved these changes

2023-10-03 05:44 UTC, boat1603 approved these changes

2023-10-03 05:44 UTC, merged